// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAzyDxL8bFwgUSpt4gMObRVxsSY9uDdps',
    appId: '1:512440099861:web:c23d0829acb83526d89a1c',
    messagingSenderId: '512440099861',
    projectId: 'rota-segura-app',
    authDomain: 'rota-segura-app.firebaseapp.com',
    storageBucket: 'rota-segura-app.appspot.com',
    measurementId: 'G-YMRXB5DT8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN7JeveDlflfHgYmw5O3YhbGkLZprg5kQ',
    appId: '1:512440099861:android:07e0aba257eb5d5fd89a1c',
    messagingSenderId: '512440099861',
    projectId: 'rota-segura-app',
    storageBucket: 'rota-segura-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAprlmI1_vFdUBjnpc3QjgkC-gjizcS9E',
    appId: '1:512440099861:ios:524b2b9c15f2a5bbd89a1c',
    messagingSenderId: '512440099861',
    projectId: 'rota-segura-app',
    storageBucket: 'rota-segura-app.appspot.com',
    iosBundleId: 'com.example.rotaSegura',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAprlmI1_vFdUBjnpc3QjgkC-gjizcS9E',
    appId: '1:512440099861:ios:524b2b9c15f2a5bbd89a1c',
    messagingSenderId: '512440099861',
    projectId: 'rota-segura-app',
    storageBucket: 'rota-segura-app.appspot.com',
    iosBundleId: 'com.example.rotaSegura',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAzyDxL8bFwgUSpt4gMObRVxsSY9uDdps',
    appId: '1:512440099861:web:6ad6628490e43a46d89a1c',
    messagingSenderId: '512440099861',
    projectId: 'rota-segura-app',
    authDomain: 'rota-segura-app.firebaseapp.com',
    storageBucket: 'rota-segura-app.appspot.com',
    measurementId: 'G-T0622XQ8R3',
  );
}
